repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff
    rev: v0.0.241
    hooks:
      - id: ruff
        args: ["--extend-select", "B", "I", "RUF", "UP"]

  - repo: https://github.com/charliermarsh/ruff
    rev: v0.0.241
    hooks:
      - id: ruff-format
